/* ============================================================
   ScholarConnect - Sample Data
   Fictional scholarship dataset for demo purposes only.
   This is what a real backend/database would eventually serve.
   ============================================================ */

const SCHOLARSHIPS = [
  {
    id: 1,
    name: "Horizon Merit Scholarship",
    provider: "Horizon Education Trust",
    amount: 75000,
    deadline: "2026-12-15",
    educationLevel: ["Undergraduate"],
    fields: ["Engineering", "Computer Science"],
    states: ["Maharashtra", "Karnataka", "Gujarat"],
    maxIncome: 800000,
    minimumPercentage: 75,
    category: "Merit",
    gender: "All",
    type: "Private",
    description: "Awarded to undergraduate engineering and CS students with strong academic records, renewable each year based on continued performance.",
    documents: ["Marksheet", "Income Certificate", "ID Proof", "Bonafide Certificate"],
    process: "Apply online with academic transcripts; shortlisted candidates attend a short interview."
  },
  {
    id: 2,
    name: "She Leads STEM Grant",
    provider: "Nirmaan Foundation",
    amount: 100000,
    deadline: "2026-11-05",
    educationLevel: ["Undergraduate", "Postgraduate"],
    fields: ["Engineering", "Computer Science", "Mathematics", "Physics"],
    states: ["All India"],
    maxIncome: 1000000,
    minimumPercentage: 65,
    category: "Women in Education",
    gender: "Female",
    type: "Foundation",
    description: "Supports women pursuing STEM degrees, with a focus on first-generation learners and applicants from underrepresented regions.",
    documents: ["Marksheet", "Income Certificate", "ID Proof", "Statement of Purpose"],
    process: "Submit a 500-word statement of purpose along with academic records; no interview required."
  },
  {
    id: 3,
    name: "National Merit-cum-Means Scholarship",
    provider: "Ministry of Higher Education",
    amount: 50000,
    deadline: "2026-10-20",
    educationLevel: ["Undergraduate"],
    fields: ["All Fields"],
    states: ["All India"],
    maxIncome: 350000,
    minimumPercentage: 60,
    category: "Government",
    gender: "All",
    type: "Government",
    description: "A government scheme supporting meritorious students from economically weaker sections across all disciplines.",
    documents: ["Income Certificate", "Marksheet", "Caste/Category Certificate (if applicable)", "Bank Passbook Copy"],
    process: "Apply through the National Scholarship Portal; verification is done at the institution level."
  },
  {
    id: 4,
    name: "Coastal Futures Research Fellowship",
    provider: "Address Maker Foundation",
    amount: 150000,
    deadline: "2027-01-10",
    educationLevel: ["Postgraduate", "Doctoral"],
    fields: ["Environmental Science", "Urban Planning", "Civil Engineering"],
    states: ["Maharashtra", "Goa", "Kerala"],
    maxIncome: 1200000,
    minimumPercentage: 70,
    category: "Research",
    gender: "All",
    type: "Foundation",
    description: "Funds original research into coastal urban development, climate resilience, and sustainable land use.",
    documents: ["Research Proposal", "Marksheet", "Recommendation Letter", "ID Proof"],
    process: "Submit a 2-page research proposal; shortlisted applicants present to a review panel."
  },
  {
    id: 5,
    name: "First Step First-Gen Scholarship",
    provider: "Udaan Trust",
    amount: 40000,
    deadline: "2026-11-30",
    educationLevel: ["Undergraduate"],
    fields: ["All Fields"],
    states: ["All India"],
    maxIncome: 400000,
    minimumPercentage: 55,
    category: "Financial Need",
    gender: "All",
    type: "Foundation",
    description: "Dedicated to first-generation college students who are the first in their family to pursue higher education.",
    documents: ["Income Certificate", "Marksheet", "Self-Declaration Form", "ID Proof"],
    process: "Online application with a short essay on educational background; no entrance test."
  },
  {
    id: 6,
    name: "Chess & Chalkboard Sports Scholarship",
    provider: "Vardaan Sports Society",
    amount: 35000,
    deadline: "2026-12-01",
    educationLevel: ["Undergraduate", "Postgraduate"],
    fields: ["All Fields"],
    states: ["All India"],
    maxIncome: 900000,
    minimumPercentage: 50,
    category: "Sports",
    gender: "All",
    type: "Foundation",
    description: "Recognises students who have represented their state or national teams while maintaining academic standing.",
    documents: ["Sports Certificate", "Marksheet", "ID Proof"],
    process: "Submit sports achievement proof alongside academic records for committee review."
  },
  {
    id: 7,
    name: "Canvas & Craft Arts Grant",
    provider: "Kalakriti Foundation",
    amount: 45000,
    deadline: "2026-10-25",
    educationLevel: ["Undergraduate"],
    fields: ["Fine Arts", "Design", "Architecture"],
    states: ["All India"],
    maxIncome: 700000,
    minimumPercentage: 55,
    category: "Arts",
    gender: "All",
    type: "Foundation",
    description: "Supports students of fine arts, design, and architecture with a portfolio-based selection process.",
    documents: ["Portfolio", "Marksheet", "Income Certificate"],
    process: "Submit a digital portfolio of up to 10 works along with academic records."
  },
  {
    id: 8,
    name: "Aspire Girls' Education Bursary",
    provider: "Roshni Welfare Society",
    amount: 60000,
    deadline: "2026-11-18",
    educationLevel: ["Class 11-12", "Undergraduate"],
    fields: ["All Fields"],
    states: ["Maharashtra", "Rajasthan", "Uttar Pradesh"],
    maxIncome: 300000,
    minimumPercentage: 50,
    category: "Women in Education",
    gender: "Female",
    type: "Foundation",
    description: "A need-based bursary for girls at risk of dropping out of school or college due to financial constraints.",
    documents: ["Income Certificate", "Marksheet", "Domicile Certificate"],
    process: "Application reviewed by local counsellor; disbursed directly to the institution."
  },
  {
    id: 9,
    name: "TechBridge Computer Science Award",
    provider: "TechBridge India",
    amount: 90000,
    deadline: "2027-02-01",
    educationLevel: ["Undergraduate"],
    fields: ["Computer Science", "Information Technology"],
    states: ["All India"],
    maxIncome: 1000000,
    minimumPercentage: 70,
    category: "STEM",
    gender: "All",
    type: "Private",
    description: "Backed by a technology company, this award supports promising CS/IT undergraduates and offers a mentorship track.",
    documents: ["Marksheet", "ID Proof", "Statement of Purpose"],
    process: "Online application followed by a technical aptitude screening for shortlisted candidates."
  },
  {
    id: 10,
    name: "Rural Reach Scholarship",
    provider: "Gram Vikas Sansthan",
    amount: 30000,
    deadline: "2026-11-10",
    educationLevel: ["Undergraduate"],
    fields: ["All Fields"],
    states: ["Maharashtra", "Madhya Pradesh", "Bihar"],
    maxIncome: 250000,
    minimumPercentage: 50,
    category: "Financial Need",
    gender: "All",
    type: "NGO",
    description: "Targeted at students from rural and semi-urban backgrounds pursuing their first undergraduate degree.",
    documents: ["Income Certificate", "Domicile Certificate", "Marksheet"],
    process: "Application verified through a partner NGO field visit before disbursement."
  },
  {
    id: 11,
    name: "State Merit Scholarship for Higher Studies",
    provider: "State Directorate of Education",
    amount: 55000,
    deadline: "2026-10-30",
    educationLevel: ["Undergraduate", "Postgraduate"],
    fields: ["All Fields"],
    states: ["Maharashtra"],
    maxIncome: 600000,
    minimumPercentage: 65,
    category: "Government",
    gender: "All",
    type: "Government",
    description: "A state-run scheme rewarding academic merit for residents pursuing higher education within the state.",
    documents: ["Domicile Certificate", "Marksheet", "Income Certificate"],
    process: "Apply via the state scholarship portal; disbursed in two instalments."
  },
  {
    id: 12,
    name: "Enable & Excel Disability Support Grant",
    provider: "Sahyog Foundation",
    amount: 65000,
    deadline: "2026-12-20",
    educationLevel: ["Undergraduate", "Postgraduate"],
    fields: ["All Fields"],
    states: ["All India"],
    maxIncome: 900000,
    minimumPercentage: 50,
    category: "Financial Need",
    gender: "All",
    type: "Foundation",
    description: "Provides financial and assistive-technology support for students with disabilities pursuing higher education.",
    documents: ["Disability Certificate", "Marksheet", "Income Certificate"],
    process: "Application with disability certification; committee review within three weeks."
  },
  {
    id: 13,
    name: "MBA Momentum Scholarship",
    provider: "Concord Business School Trust",
    amount: 200000,
    deadline: "2027-01-25",
    educationLevel: ["Postgraduate"],
    fields: ["Business Administration", "Management"],
    states: ["All India"],
    maxIncome: 1500000,
    minimumPercentage: 60,
    category: "Merit",
    gender: "All",
    type: "Private",
    description: "Covers a significant share of tuition for incoming MBA students with strong leadership potential.",
    documents: ["Marksheet", "Entrance Score Card", "Statement of Purpose"],
    process: "Shortlisting based on entrance scores, followed by a panel interview."
  },
  {
    id: 14,
    name: "GreenPath Environmental Studies Award",
    provider: "EcoNext Alliance",
    amount: 48000,
    deadline: "2026-11-22",
    educationLevel: ["Undergraduate", "Postgraduate"],
    fields: ["Environmental Science", "Sustainability Studies"],
    states: ["All India"],
    maxIncome: 850000,
    minimumPercentage: 60,
    category: "STEM",
    gender: "All",
    type: "NGO",
    description: "Supports students committed to environmental and sustainability careers, with preference for field-research experience.",
    documents: ["Marksheet", "Income Certificate", "Statement of Purpose"],
    process: "Written application; no interview for awards under ₹50,000."
  },
  {
    id: 15,
    name: "Foundation Scholars Programme",
    provider: "Forum Community Trust",
    amount: 120000,
    deadline: "2027-02-15",
    educationLevel: ["Undergraduate"],
    fields: ["All Fields"],
    states: ["Maharashtra", "Karnataka"],
    maxIncome: 500000,
    minimumPercentage: 65,
    category: "Merit",
    gender: "All",
    type: "Foundation",
    description: "A flagship programme offering multi-year support to meritorious students from low-income households.",
    documents: ["Income Certificate", "Marksheet", "ID Proof", "Recommendation Letter"],
    process: "Two-stage process: written application, then a home-verification interview."
  },
  {
    id: 16,
    name: "Legal Eagles Scholarship",
    provider: "Nyaya Path Foundation",
    amount: 55000,
    deadline: "2026-12-05",
    educationLevel: ["Undergraduate"],
    fields: ["Law"],
    states: ["All India"],
    maxIncome: 700000,
    minimumPercentage: 60,
    category: "Merit",
    gender: "All",
    type: "Foundation",
    description: "Supports law undergraduates with a demonstrated interest in public interest litigation and legal aid work.",
    documents: ["Marksheet", "Income Certificate", "Statement of Purpose"],
    process: "Application with a short essay on a public-interest legal issue."
  }
];

/* Category metadata used to render the visual category strip */
const CATEGORIES = [
  "Merit", "Financial Need", "STEM", "Women in Education",
  "Sports", "Arts", "Research", "Government", "Foundation"
];
